name: Manual Web Scraping-save

on:
  workflow_dispatch:
    inputs:
      script:
        description: 'Path to the scraping script'
        required: true
        default: 'js.py'

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Repository
        uses: actions/checkout@v2

      - name: Set Up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          pip install requests beautifulsoup4 pandas

      - name: Run Web Scraping Script
        run: |
          python ${{ github.event.inputs.script }}

      - name: Generate JSON and CSV Files
        run: |
          # Run your script that generates JSON and CSV files
          python ${{ github.event.inputs.script }}
        working-directory: .

      - name: Commit and Push JSON and CSV Files
        run: |
          git config user.name "GitHub Actions"
          git config user.email "<actions@users.noreply.github.com>"
          git add your-json-file.json your-csv-file.csv
          git commit -m "Update JSON and CSV files $(date -u +'%Y-%m-%d %H:%M:%S')"
          git push https://${{ secrets.PAT_TOKEN }}@github.com/az-my/scrape-the-job.git
