name: Run Carikerja.py

on:
  schedule:
    - cron: "1 17 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Pull latest changes
        run: git pull

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          pip install requests
          pip install beautifulsoup4

      - name: Run Cari Kerja
        run: python carikerja.py

      - name: Commit and push data changes
        run: |
          git config --global user.name "Your Name"
          git config --global user.email "your.email@example.com"

          for file in extracted_data.json transformed_data.json filtered_data.json; do
            git add $file
            if git diff-index --quiet HEAD --; then
              echo "No changes in $file"
            else
              git commit -m "Update $file" && git push
            fi
          done
