name: Manual Web Scraping-jsv2

on:
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Repository
        uses: actions/checkout@v2

      - name: Set Up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Replace with your desired Python version

      - name: Install Dependencies
        run: |
          pip install requests beautifulsoup4 pandas
        # Continue with the rest of your workflow...
        
      - name: Run Web Scraping Script
        run: |
          python js.py  # Replace with your script's name
          
      - name: Commit and Push Changes
        run: |
          git config user.name "az-my"
          git config user.email "jkiaceh@gmail.com"
          git add .
          git commit -m "Update scraped data $(date -u +'%Y-%m-%d %H:%M:%S')"
          git push https://${{ secrets.PAT_TOKEN }}@github.com/az-my/scrape-the-job.git
