name: Manual Web Scraping

on:
  workflow_dispatch:
    inputs:
      script:
        description: 'Path to the scraping script'
        required: true
        default: 'js.py'

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Repository
        uses: actions/checkout@v2

      - name: Set Up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          pip install requests beautifulsoup4 pandas
        continue

      - name: Run Web Scraping Script
        run: |
          python ${{ github.event.inputs.script }}
