name: Manual Web Scraping

on:
  workflow_dispatch:
    inputs:
      replace-files:
        description: 'Replace existing JSON and CSV files (true/false)'
        required: true
        default: 'false'

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Repository
        uses: actions/checkout@v2

      - name: Set Up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          pip install requests beautifulsoup4 pandas

      - name: Run Web Scraping Script
        run: |
          python js.py

      - name: Generate JSON and CSV
        run: |
          python js.py
          if [ "${{ github.event.inputs.replace-files }}" = "true" ]; then
            mv -f job_data.json $GITHUB_WORKSPACE/job_data.json
            mv -f job_data.csv $GITHUB_WORKSPACE/job_data.csv
          fi

      - name: Commit and Push Changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "<actions@users.noreply.github.com>"
          git add job_data.json job_data.csv
          git commit -m "Auto-generate JSON and CSV files"
          git push https://${{ secrets.GITHUB_TOKEN }}@github.com/az-my/scrape-the-job.git main
